### ISSUE TITLE
shouldn't realllllly be doing dependency verification as part of the app's production code…

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-express#105]
this stuff really _ought_ to be part of the `next-build-tools verify` logic.
https://github.com/Financial-Times/next-express/blob/master/main.js#L105-110

related to: https://github.com/Financial-Times/next-build-tools/issues/68

not a priority.

**Comment by matthew-andrews** [comment]
cc @wheresrhys

**Comment by wheresrhys** [comment]
Aargh, yes quite right. Is 'fixing a problem in the file you happen to have
open at the time' a documented anti pattern I wonder.

Will move it into nbt today

On Sunday, April 26, 2015, Matt Andrews <notifications@github.com> wrote:

> cc @wheresrhys <https://github.com/wheresrhys>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/next-express/issues/105#issuecomment-96295729>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by matthew-andrews** [comment]
it's not urgent :)
