### ISSUE TITLE
deprecate app specific service dependency registration

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-express#207]
Because 
- duplication between apps, e.g. if only one app uses video.ft.com now, then if another uses it later it must also define it. Simpler and harmless to just define in one shared location
- possible misleading overlap of names e.g. 1 app calls our brightcove proxy 'brightcove', another app calls brightcove directly, calling it 'brightcove'
- if we move towards having service dependencies as a part of service registry (which I think we should, even for services we don't host, as it'd result in a single source of information to generate a complete dependency tree) then allowing apps to add to this list on the fly decreases the comprehensiveness, and thus the usefulness, of such a thing

**Comment by matthew-andrews** [comment]
yup ok.  you wanna do this or want us to pick this up as we map out dependency tree?
