### ISSUE TITLE
Change deprecated install step

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/next-express#226]
In https://github.com/Financial-Times/next-express#installation, the `bower-install.sh` file doesn't exist anymore:

> When using the default layout there is also a hard dependency on some bower components. To install them (and add to your app's bower.json) run the following on your local machine. It's assumed you will have bower installed globally.
> 
> $ ./path/to/ft-next-express/bower-install.sh

**Comment by matthew-andrews** [comment]
https://github.com/Financial-Times/next-express/pull/300/files
