### ISSUE TITLE
Define a layout

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-express#24]
Just seen from https://github.com/ericf/express-handlebars that it does support very limited inheritance in order to define a page layout. As next express is always a direct dependency we will always know the path to it, so can safely define `app.locals.layout = ./node_modules/ft-next express/layout`.

**Comment by matthew-andrews** [comment]
hmm…  the problem is it might be `./node_modules/ft-next-next-express/node_modules/ft-next-express/layout`.

could we put inside `ft-next-wrapper`?

**Comment by matthew-andrews** [comment]
if not then i'm fine with this, but make sure to write a test :)

**Comment by wheresrhys** [comment]
I was thinking of deprecating wrapper properly.

how about `app.locals.layout = ./node_modules/ft-next express/layout` as an overridable default?

**Comment by matthew-andrews** [comment]
you should be able to figure out where you are actually based on a mixture of `__dirname` and `directory` 
https://github.com/Financial-Times/next-express/blob/master/main.js#L42

**Comment by wheresrhys** [comment]
done in https://github.com/Financial-Times/next-express/pull/25
